platform:ios,'10.0'

use_frameworks!
inhibit_all_warnings!

target 'V2EX-Swift' do

pod 'Moya'
pod 'Ji'
pod 'Kingfisher'
pod 'SnapKit'
pod 'GDPerformanceView-Swift', :configurations => ['Debug']
pod 'MJRefresh'
pod 'MarkdownView'
pod 'MonkeyKing'

end

target 'V2EX-Hot' do
  
  pod 'Moya'
  pod 'Kingfisher'
  
end
