platform:ios,'10.0'

use_frameworks!
inhibit_all_warnings!

target 'V2EX-Swift' do

pod 'Moya'
pod 'Ji'
pod 'Kingfisher'
pod 'SnapKit'
pod 'MonkeyKing'
pod 'GDPerformanceView-Swift', :configurations => ['Debug']

end
