# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'v2ex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for v2ex
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Ono'
  
end
